arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
# 指定生成的类名
output-class: AppLocalizations
# Optional: Specify a file to write the list of supported locales to.
# header-file: app_localizations_header.dart
# Optional: Specify whether to use deferred loading for web.
# deferred-loading: false
